#!/usr/bin/env bash
# installation of nginx server

sudo apt update
sudo apt -y install

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
#restart nginx
sudo service nginx restart
