#!/usr/bin/env bash
# installation of nginx server

sudo apt update
sudo apt -y install

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-enabled/default

#restart nginx
sudo service nginx restart
