#!/bin/bash/env bash

# Install Nginx
apt-get update
apt-get install nginx -y

# Configure Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}" > /etc/nginx/sites-available/default

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test the Nginx configuration and restart the service
nginx -t
service nginx restart

echo "Nginx configured to listen on port 80."

