#!/usr/bin/env bash
# Initialize variables for hours and minutes

hour=0

while [ $hour -le 12 ]
do
  if [ $hour -eq 0 ]; then
    echo "Hour: 0"
  else
    echo "Hour: $hour"
  fi

  minute=1
  while [ $minute -le 59 ]
  do
    echo $minute
    minute=$((minute + 1))
  done

  hour=$((hour + 1))
done | head -n 70
